on: [push, pull_request]

name: Continuous integration

jobs:
  check:
    strategy:
      matrix:
        toolchain: [stable, nightly]
        os: [windows-latest, ubuntu-latest, macos-latest]
        exclude:
          - os: macos-latest
            toolchain: nightly
          - os: windows-latest
            toolchain: nightly
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo check
#  test:
#    strategy:
#      matrix:
#        toolchain: [stable]
#        os: [ubuntu-latest]
#        exclude:
#          - os: macos-latest
#            toolchain: nightly
#          - os: windows-latest
#            toolchain: nightly
#    name: Test Suite
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions-rs/toolchain@v1
#        with:
#          profile: minimal
#          toolchain: stable
#          override: true
#      - run: cargo test
